name: RadioLuzia
options:
  bundleIdPrefix: br.com.cloudbrapp
  deploymentTarget:
    iOS: "18.0"
settings:
  base:
    SWIFT_VERSION: 6.0
    DEVELOPMENT_TEAM: DHLAYBVJ2Z
targets:
  RadioLuzia:
    type: application
    platform: iOS
    sources:
      - path: RadioLuzia
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: br.com.cloudbrapp.radioluzia
        CURRENT_PROJECT_VERSION: 2
        INFOPLIST_FILE: RadioLuzia/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    scheme:
      testTargets:
        - RadioLuziaTests
  RadioLuziaTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RadioLuziaTests
    dependencies:
      - target: RadioLuzia
